version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_salesforce_opportunities
      - name: raw_salesforce_accounts
      - name: raw_product_events
      - name: raw_billing_invoices
      - name: raw_billing_subscriptions
